name: calculator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  flutter_simple_calculator: ^2.0.0-nullsafety.1
  get: 4.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.3
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

flutter: 
  uses-material-design: true

